# infra/base/kustomization.yaml
resources:
  - backend-deployment.yaml
  - backend-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - ingress.yaml
  - secret.yaml
  - configmap.yaml
  
  

